#!/usr/bin/env python3
"""
Pune (PMPML) specific utilities for GTFS processing.

Provides the route_short_name -> route_id(s) mapping used by
functions/api/pmpml to filter the PMPML GTFS-RT VehiclePositions feed by
the public route number (e.g. "220").
"""
import csv
import io
import json
import os
import urllib.request
import zipfile
from collections import defaultdict
from pathlib import Path
from typing import Dict
import polars as pl

# Repo root is three levels up from data/pune/utils.py
_REPO_ROOT = Path(__file__).parent.parent.parent
_JS_OUTPUT_PATH = _REPO_ROOT / 'functions' / 'api' / 'pmpml' / 'pmpml-route-mapping.js'

# The GTFS-RT feed's route_id is an internal id assigned by the same
# publisher (BLRTransit) that also ships a static companion GTFS feed at
# rt/control/static/gtfs.zip on the same host - and that static feed's
# route_id values are exactly the ones the realtime feed uses (confirmed by
# cross-referencing live VehiclePosition entries against chartr's own
# per-route APIs, which return matching route_id/route_long_name pairs).
# This is a different, unrelated numbering space from `gtfs_data` (the
# community-built static feed in data/sources.json used to render the map),
# whose route_id happens to equal route_short_name instead - so this
# fetches its own feed rather than deriving the mapping from gtfs_data.
_STATIC_GTFS_URL = 'https://rt-bucket.blrtransit.com/rt/control/static/gtfs.zip'


def _fetch_routes_csv() -> str:
    request = urllib.request.Request(
        _STATIC_GTFS_URL,
        headers={
            'User-Agent': (
                'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:144.0) '
                'Gecko/20100101 Firefox/144.0'
            ),
        },
    )
    with urllib.request.urlopen(request, timeout=60) as res:
        data = res.read()
    with zipfile.ZipFile(io.BytesIO(data)) as zf:
        with zf.open('routes.txt') as f:
            return f.read().decode('utf-8-sig')


def generate_mapping(gtfs_data: Dict[str, pl.DataFrame], output_dir: str) -> None:
    """Generate route_short_name -> route_id(s) mapping for PMPML.

    Each route is usually split into two directional rows (UP/DOWN) with
    distinct route_id values sharing the same route_short_name, so the
    mapping values are lists.

    Writes mapping.min.json to output_dir and a JS module to the Cloudflare
    Functions directory so vehicles.js/stop-vehicles.js can import it
    without a runtime fetch.
    """
    print(f'PMPML: Fetching {_STATIC_GTFS_URL}...')
    try:
        routes_csv = _fetch_routes_csv()
    except Exception as e:
        print(f"PMPML: Failed to fetch {_STATIC_GTFS_URL}: {e}")
        return

    mapping = defaultdict(list)
    for row in csv.DictReader(io.StringIO(routes_csv)):
        route_id = (row.get('route_id') or '').strip()
        short_name = (row.get('route_short_name') or '').strip()
        if not route_id or not short_name:
            continue
        if route_id not in mapping[short_name]:
            mapping[short_name].append(route_id)
    mapping = dict(mapping)

    if not mapping:
        print("PMPML: No routes found, skipping mapping generation")
        return

    json_path = os.path.join(output_dir, 'mapping.min.json')
    with open(json_path, 'w') as f:
        json.dump(mapping, f, separators=(',', ':'))
    print(f"PMPML: Generated route name mapping: {len(mapping)} entries -> {json_path}")

    js_content = (
        "// Auto-generated by data/pune/utils.py — do not edit manually\n"
        "// Maps a public PMPML route number (route_short_name) to the\n"
        "// GTFS-RT route_id(s) that identify it in the VehiclePositions feed\n"
        "// (see generate_mapping for why this mapping is needed).\n"
        f"export default {json.dumps(mapping, separators=(',', ':'))};\n"
    )
    with open(_JS_OUTPUT_PATH, 'w') as f:
        f.write(js_content)
    print(f"PMPML: Generated route mapping JS module -> {_JS_OUTPUT_PATH}")
