#!/usr/bin/env python3
"""
BLR (Bangalore) specific utilities for GTFS processing.

Provides city-specific customizations for stop name generation.
"""
import json
import os
import polars as pl
from pathlib import Path
from typing import Dict, Set, List

# Repo root is three levels up from data/blr/utils.py
_REPO_ROOT = Path(__file__).parent.parent.parent
_JS_OUTPUT_PATH = _REPO_ROOT / 'functions' / 'api' / 'bmtc' / 'blr-route-mapping.js'


def generate_mapping(gtfs_data: Dict[str, pl.DataFrame], output_dir: str) -> None:
    """Generate route_short_name -> route_id mapping for BLR.

    Writes mapping.min.json to output_dir and a JS module to the Cloudflare
    Functions directory so arrivals.js can import it without a runtime fetch.
    Falls back to route_id when route_short_name is absent or empty.
    """
    routes_df = gtfs_data.get('routes', pl.DataFrame())
    if routes_df.is_empty():
        return

    has_short_name = 'route_short_name' in routes_df.columns
    mapping = {}
    for row in routes_df.to_dicts():
        route_id = row['route_id']
        route_name = None
        if has_short_name:
            short = row.get('route_short_name')
            if short and str(short).strip():
                route_name = str(short).strip()
        mapping[route_name or route_id] = route_id

    json_path = os.path.join(output_dir, 'mapping.min.json')
    with open(json_path, 'w') as f:
        json.dump(mapping, f, separators=(',', ':'))
    print(f"BLR: Generated route name mapping: {len(mapping)} entries -> {json_path}")

    js_content = (
        "// Auto-generated by data/blr/utils.py — do not edit manually\n"
        f"export default {json.dumps(mapping, separators=(',', ':'))};\n"
    )
    with open(_JS_OUTPUT_PATH, 'w') as f:
        f.write(js_content)
    print(f"BLR: Generated route mapping JS module -> {_JS_OUTPUT_PATH}")


def process_stop_names(
    stops_dict: Dict[str, List],
    gtfs_data: Dict[str, pl.DataFrame],
    valid_routes: Set[str]
) -> Dict[str, List]:
    """
    Process stop names to add stop_desc as suffix for disambiguation.

    Reads the stop_desc column from stops.txt in the GTFS data and uses it
    as the suffix field for each stop.

    Args:
        stops_dict: Dictionary of stop_id -> [lon, lat, name, suffix]
        gtfs_data: Dictionary containing GTFS DataFrames
        valid_routes: Set of valid route IDs

    Returns:
        Modified stops_dict with updated suffixes
    """
    print("BLR: Adding suffixes from stop_desc to disambiguate stop names...")

    stops_df = gtfs_data.get('stops', pl.DataFrame())
    if stops_df.is_empty() or 'stop_desc' not in stops_df.columns:
        print("  No stop_desc column found in stops data, skipping suffix generation")
        return stops_dict

    stop_desc_map = {
        row['stop_id']: row['stop_desc']
        for row in stops_df.select(['stop_id', 'stop_desc']).to_dicts()
        if row['stop_desc']
    }

    updated = 0
    for stop_id, desc in stop_desc_map.items():
        if stop_id not in stops_dict:
            continue
        towards = '(Towards '
        start = desc.find(towards)
        if start == -1:
            continue
        start += len(towards)
        end = desc.rfind(')')
        if end <= start:
            continue
        stops_dict[stop_id][3] = f"(Towards {desc[start:end]})"
        updated += 1

    print(f"  Updated {updated} stops with stop_desc suffixes")
    return stops_dict
