#!/usr/bin/env python3
"""
Delhi (DTC) specific utilities for GTFS processing.

Provides the route_short_name -> route_id(s) mapping used by
functions/api/delhi to filter the Delhi GTFS-RT VehiclePositions feed by
the public route number, similar in spirit to
functions/api/pmpml/utils.py.
"""
import json
import os
from collections import defaultdict
from pathlib import Path
from typing import Dict
import polars as pl

# Repo root is three levels up from data/delhi/utils.py
_REPO_ROOT = Path(__file__).parent.parent.parent
_JS_OUTPUT_PATH = _REPO_ROOT / 'functions' / 'api' / 'delhi' / 'delhi-route-mapping.js'


def generate_mapping(gtfs_data: Dict[str, pl.DataFrame], output_dir: str) -> None:
    """Generate route_short_name -> route_id(s) mapping for Delhi (DTC).

    The realtime feed is served by dts-backend.transportstack.in for
    agency=delhi-buses, category=realtime_gtfs. Its route_id matches the
    route_id in the static GTFS for the same agency (this is a proper
    OTD/transportstack dataset, where static and realtime feeds for one
    agency are published together and share ids by construction - unlike
    PMPML's realtime feed, which is a third party republishing an unrelated
    static feed's data under different ids). That static feed is the same
    one already loaded into `gtfs_data` for the main pipeline (the vendored
    zip in data/delhi/), so this reuses it rather than re-fetching.

    Each route is usually split into two directional rows (UP/DOWN, or a
    directional suffix folded into the name itself, e.g. "U-SPL-25UP")
    with distinct route_id values sharing the same route_short_name, so the
    mapping values are lists.

    Writes mapping.min.json to output_dir and a JS module to the Cloudflare
    Functions directory so vehicles.js can import it without a runtime fetch.
    """
    routes_df = gtfs_data.get('routes', pl.DataFrame())
    if routes_df.is_empty():
        return

    mapping = defaultdict(list)
    for row in routes_df.to_dicts():
        route_id = str(row.get('route_id') or '').strip()
        short_name = str(row.get('route_short_name') or '').strip()
        if not route_id or not short_name:
            continue
        if route_id not in mapping[short_name]:
            mapping[short_name].append(route_id)
    mapping = dict(mapping)

    if not mapping:
        print("Delhi: No routes found, skipping mapping generation")
        return

    json_path = os.path.join(output_dir, 'mapping.min.json')
    with open(json_path, 'w') as f:
        json.dump(mapping, f, separators=(',', ':'))
    print(f"Delhi: Generated route name mapping: {len(mapping)} entries -> {json_path}")

    js_content = (
        "// Auto-generated by data/delhi/utils.py — do not edit manually\n"
        "// Maps a public Delhi (DTC) route number (route_short_name) to the\n"
        "// GTFS-RT route_id(s) that identify it in the VehiclePositions feed\n"
        "// (see generate_mapping for where this mapping comes from).\n"
        f"export default {json.dumps(mapping, separators=(',', ':'))};\n"
    )
    with open(_JS_OUTPUT_PATH, 'w') as f:
        f.write(js_content)
    print(f"Delhi: Generated route mapping JS module -> {_JS_OUTPUT_PATH}")
