#!/usr/bin/env python3
"""
Precompute a global per-stop trip-frequency index from every city's
per-stop schedule files (data/{city}/schedule/{stopId}.json, generated by
schedule.py). This is the same aggregation `staticFrequency` already does
client-side for a single stop (assets/app.js), just done once at build time
for every stop in every city, so an all-mode RAPTOR search can look up an
expected-wait estimate synchronously (in-memory) instead of fetching real
schedule JSON for every stop it touches during the search - fetching
thousands of individual schedule files mid-search doesn't scale country-wide

Must run as part of the same `process.py` invocation that generates each
city's `schedule/` directory - `pnpm run data`'s later cleanup step
(`rm -Rf dist/data/*/schedule`) deletes those directories before the dist
bundle ships, so this aggregation only has data to read right after
schedule.py runs, not on a rebuild from a checked-out dist/.

Output: data/all/frequency.min.json -> { "city^stop_id": { "service_no": total_daily_trip_count, ... }, ... }
"""

import json
from pathlib import Path
from typing import Dict

SCRIPT_DIR = Path(__file__).parent
OUTPUT_DIR = SCRIPT_DIR / 'all'
OUTPUT_FILE = OUTPUT_DIR / 'frequency.min.json'


def discover_schedule_dirs() -> Dict[str, Path]:
    """Return {city_code: path/to/schedule_dir} for every city with a schedule/ dir."""
    cities = {}
    for item in sorted(SCRIPT_DIR.iterdir()):
        if not item.is_dir() or item.name.startswith('.') or item.name == 'all':
            continue
        schedule_dir = item / 'schedule'
        if schedule_dir.is_dir():
            cities[item.name] = schedule_dir
    return cities


def aggregate_stop_frequency(schedule_file: Path) -> Dict[str, int]:
    """Sum trip_count per service number across all route/direction entries
    for one stop's schedule file (mirrors app.js's staticFrequency logic)."""
    with open(schedule_file, 'r', encoding='utf-8') as f:
        data = json.load(f)

    counts: Dict[str, int] = {}
    for service in data.get('services', []):
        no = service.get('no')
        trip_count = service.get('trip_count', 0)
        if no is None or not trip_count:
            continue
        key = str(no)
        counts[key] = counts.get(key, 0) + trip_count
    return counts


def main():
    schedule_dirs = discover_schedule_dirs()
    if not schedule_dirs:
        print('No schedule/ directories found - nothing to aggregate (skipping).')
        return 0

    print(f'Found schedule data for {len(schedule_dirs)} cities: {", ".join(sorted(schedule_dirs))}')

    frequency: Dict[str, Dict[str, int]] = {}
    for city, schedule_dir in schedule_dirs.items():
        for schedule_file in schedule_dir.glob('*.json'):
            stop_id = schedule_file.stem
            counts = aggregate_stop_frequency(schedule_file)
            if counts:
                frequency[f'{city}^{stop_id}'] = counts

    print(f'Aggregated frequency data for {len(frequency):,} stops')

    OUTPUT_DIR.mkdir(exist_ok=True)
    frequency_sorted = dict(sorted(frequency.items()))
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        json.dump(frequency_sorted, f, separators=(',', ':'))
    print(f'Wrote: {OUTPUT_FILE}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())